// <auto-generated />
using System;
using CourseLanding.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseLanding.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CourseLandingDbContext))]
    [Migration("20260204120000_AddLeads")]
    partial class AddLeads
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseLanding.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                    b.Property<int>("DurationHours").HasColumnType("int");
                    b.Property<bool>("IsPublished").HasColumnType("bit");
                    b.Property<string>("Language").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Level").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Subtitle").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("CourseLanding.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("CourseId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("nvarchar(320)");
                    b.Property<string>("Name").HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Source").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("CourseId");
                    b.HasIndex("CourseId", "Email");
                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("CourseLanding.Domain.Entities.Lead", b =>
                {
                    b.HasOne("CourseLanding.Domain.Entities.Course", "Course")
                        .WithMany("Leads")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
